[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[sudo]
format = '\[[as $symbol]\]'

[time]
format = '\[[$time]($style)\]'

[username]
style_user = "white bold"
style_root = "black bold"
format = '\[[$user]($style)\]'
show_always = true

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[battery]
full_symbol = ""
charging_symbol = "⚡️"
discharging_symbol = ""

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = ""

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = false

